version: '3.8'
services:
  app:
    container_name: gm_tool_backend
    build: .
    ports: 
      - 8080:8000 
    restart: on-failure
    volumes:
      - ./api:/usr/src/app/
    depends_on:
      - fullstack-mysql          


  fullstack-mysql:
    image: mysql:5.7
    container_name: full_db_mysql
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_DATABASE=${DB_DATABASE}
      # - MYSQL_USER=${DB_USER_NAME}
      # - MYSQL_PASSWORD=${DB_PASSWORD}
      # - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ./database_mysql:/var/lib/mysql 
      - ./db:/docker-entrypoint-initdb.d