version: '3.3'
services:
  backend:
    container_name: gm_tool_backend
    build: 
      context: ./test5
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - fullstack-mysql          

  frontend:
    container_name: gm_tool_frontend
    build: 
     context: ./lokapala-gmtool-frontend
     dockerfile: Dockerfile
    ports: 
      - '3000:80' 
    restart: on-failure 

  fullstack-mysql:
    image: mysql:latest
    container_name: full_db_mysql
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./database_mysql:/var/lib/mysql 
      - ./db:/docker-entrypoint-initdb.d